### ISSUE TITLE
DXF files will not load into LibreCAD nor FreeCAD

### ISSUE THREAD

**Issue by dlarue** [DesignAndMake/CraftCNC#1]
I tried to determine the max sheet dimensions for our laser cutter but neither of my CAD programs can read the DXF files.  I can open DXF files from other projects without issue.

Looking at the downloaded file it appears to not be DXF file format but instead it's the Github view. ie the link is not pointing to the RAW data file.

If I go to github and get the raw data file(DXF format) it will open in LibreCAD and FreeCAD.

**Comment by Baldricktrousers** [comment]
Hi Doug
If you right click over the Dfx file it should offer you the option to save as target file.
From the drop down, Select dxf and save to your pc this should then open correctly.

Let me know if you have any issues and I will take another look

Hope this helps

**Comment by Baldricktrousers** [comment]
Hi Doug 
Thanks for the info.
The dimensions for the laser are based on 600x400mm bed size 
Hope this helps.

**Comment by dlarue** [comment]
Both Firefox and Chromium do the same and download the html as if you just clicked on that link which gets you to the file viewing page on github. 

For example, the link you have gets me here:
https://github.com/DesignAndMake/CraftCNC/blob/master/CraftCNC_D1/Hardware/DXF%20infromation/D1%2010mm%20sheet/D1%2010MM%20Material%20layer1.dxf


But it should be getting me here(notice raw at the beginning of the URL):
https://raw.githubusercontent.com/DesignAndMake/CraftCNC/master/CraftCNC_D1/Hardware/DXF%20infromation/D1%2010mm%20sheet/D1%2010MM%20Material%20layer1.dxf

Our laser cutter is 500mm x 300mm so it looks like we'll be splitting up moving parts around. But the biggest part still should just fit.

**Comment by Baldricktrousers** [comment]
Hi Doug 
Thanks for the update , we will change this as suggested, and good  to hear the dxf should still fit your laser.
We will supply a 500x 300 laser option, for the acrylic components, as this could be very helpful for others too.
Thanks again.

**Comment by Baldricktrousers** [comment]
Hi Doug
Changes to downloading of DXF files are done: let me know if these are all OK.
I have taken a look at reorganising the items for a 500x300 laser, however there are 2 items that are 304mm in size, so the laser will require this size cutting area for these two items. However all other items should fit on a 500x300. I have saved them as CVR files and you can download the Vectric Trial software, open the files and export as dxf, it is also possible to change the layout as you wish.

Hope this helps.

**Comment by dlarue** [comment]
I tested the layer 1 of the 10mm sheet and the file came down perfectly. Thanks.

I had seen the 304mm parts and figure the 4mm can be shaved off without effect on strength and aesthetics.
