### ISSUE TITLE
parts #11,#20 and #23 links from exploded  view( STL ) incorrect

### ISSUE THREAD

**Issue by dlarue** [DesignAndMake/CraftCNC#2]
Link #11 references( notice the "&" symbol ): 
https://github.com/DesignAndMake/CraftCNC/wiki/STL-Images-and-downloads#mb&s-motor-and-baring-support

which should be:
https://github.com/DesignAndMake/CraftCNC/wiki/STL-Images-and-downloads#mbs-motor-and-baring-support

Links #20(XAR x axis rack), #23(ZASR Z axis support right) are INOP too.

**Comment by Baldricktrousers** [comment]
Hi Doug
Thanks for the heads up.
All corrected.

Thanks again
